"""initial schema

Revision ID: ce5f3c35ce93
Revises: 
Create Date: 2025-05-10 15:35:45.273847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce5f3c35ce93'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aluno')
    op.drop_table('instrutor')
    op.drop_table('user')
    op.drop_table('veiculo')
    op.drop_table('aula')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aula',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('aluno_id', sa.INTEGER(), nullable=False),
    sa.Column('instrutor_id', sa.INTEGER(), nullable=False),
    sa.Column('veiculo_id', sa.INTEGER(), nullable=False),
    sa.Column('data_hora', sa.DATETIME(), nullable=False),
    sa.Column('observacoes', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('veiculo',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('marca', sa.VARCHAR(), nullable=False),
    sa.Column('modelo', sa.VARCHAR(), nullable=False),
    sa.Column('cor', sa.VARCHAR(), nullable=False),
    sa.Column('ano', sa.INTEGER(), nullable=False),
    sa.Column('placa', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('senha_hash', sa.VARCHAR(), nullable=False),
    sa.Column('permissoes', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instrutor',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(), nullable=False),
    sa.Column('cpf', sa.VARCHAR(), nullable=False),
    sa.Column('telefone', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('categoria', sa.VARCHAR(), nullable=True),
    sa.Column('senha_hash', sa.VARCHAR(), nullable=False),
    sa.Column('permissoes', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aluno',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(), nullable=False),
    sa.Column('cpf', sa.VARCHAR(), nullable=False),
    sa.Column('data_nascimento', sa.DATE(), nullable=False),
    sa.Column('telefone', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
